import decimal
#Sqrt()
a = decimal.Decimal(10.25).sqrt()
print("the Squre root of decimal number : ",end="")
print(a)
#exp()
b = decimal.Decimal(10.25).exp()
print("the exponent of decimal number is : ",end="")
print(b)
#ln
c = decimal.Decimal(10.25).ln()
print("the natural logarithm of decimal number is : ",end="")
print(c)
#log10
d = decimal.Decimal(10.25).log10()
print("the log10 of decimal number is : ",end="")
print(d)
#as_tuple()
e = decimal.Decimal(10.25).as_tuple()
print("The tuple form of decimal number is : ", end="")
print(e)
#fma()
f = decimal.Decimal(5).fma(2, 3)
print("The fused multiply and addition of decimal number is : ", end="")
print(f)
#compare()
g = decimal.Decimal(1.25)
print("The result of comparison using compare() is : ", end="")
print(a.compare(g))
#compare_total_mag()
h = decimal.Decimal(-10.25)
print("The result of comparison using compare_total_mag() is : ", end="")
print(a.compare_total_mag(h))
# copy_abs()
i = decimal.Decimal(9.53)
j = decimal.Decimal(-9.56)
print("The absolute value using copy_abs() is : ", end="")
print(j.copy_abs())
#copy_negate()
print("The negated value using copy_negate() is : ", end="")
print(j.copy_negate())
#copy_sign()
print("The sign effected value using copy_sign() is : ", end="")
print(i.copy_sign(j))
#min()
k = decimal.Decimal(9.53)
l = decimal.Decimal(7.43)
print("The minimum of two numbers is : ", end="")
print(k.min(l))
#max()
print("The maximum of two numbers is : ", end="")
print(k.max(l))
