String = "Welcome To New World"
print(String.lower())
print(String.upper())
print(String.find("To"))
print(String.islower())
print(String.isupper())
print(String.endswith("rld"))
print(String.startswith("Wel"))
print(String.split())
print(String.swapcase())
print(String.index('l'))
print(String.count("l"))
print(String.replace("New", "Future"))
print("--".join(["Welcome","to","New","World"]))