from datetime import datetime
print("Datetime object for Jan 15 2012:")
print(datetime(2012, 1, 15))
print("\nSpecific date and time of 9:20 pm")
print("\nLocal date and time:")
print(datetime.now())
print("\nA date without time: ")
print(datetime.date(datetime(2022, 6, 23)))
print("\nCurrent date:")
print(datetime.now().date())
print("\nTime from a datetime:")
print(datetime.time(datetime(2022, 6, 23, 18, 12)))
print("\nCurrent local time:")
print(datetime.now().time())
